import Head from "next/head";
import Link from "next/link";

import Layout from "../components/layout";
import styles from "../components/layout.module.css";

const Home: React.FC = () => {
  return (
    <Layout home>
      <Head>
        <title>Demo assignment</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Demo assignment</h1>
        <nav>
          <ul className={styles.navListContainer}>
            <li className={styles.navList}>
              <Link className={styles.navLink} href="/users">
                Users
              </Link>
            </li>
            <li className={styles.navList}>
              <Link className={styles.navLink} href="/todos">
                Todos
              </Link>
            </li>
            <li className={styles.navList}>
              <Link className={styles.navLink} href="/posts">
                Posts
              </Link>
            </li>
          </ul>
        </nav>
      </main>
    </Layout>
  );
};

export default Home;
